### ISSUE TITLE
Reset Pin? Cannot find device "wpan0"

### ISSUE THREAD

**Issue by ab0032** [nyrocron/dw1000#2]
Hi,
wir haben folgendes DWM1000 Module von Wayne Holder:
https://sites.google.com/site/wayneholder/uwb-ranging-with-the-decawave-dwm1000

Dieses haben wir an SPI0 mit einem Raspberry Pi 2 angeschlossen, jedoch verstehen wir nicht was mit dem Reset Pin zu tun ist, was ja vermutlich essentiell is um das Module zu starten. Wie muss das angeschlossen werden?

Das Kernel-Module wird installiert, jedoch gibt es kein Fehlermeldung in dmesg oder syslog und es gibt keinen Unterschied im Verhalten ob das DWM1000 Modul physikalisch angeschlossen ist oder nicht.

Für Hilfe wären wir sehr Dankbar.

decawave/dw1000$ make start
sudo insmod dw1000.ko
sudo ip link set up wpan0
Cannot find device "wpan0"
Makefile:34: recipe for target 'start' failed
make: **\* [start] Error 1

**Comment by nyrocron** [comment]
DE: Ich habe nur SPI + IRQ verbunden, den Reset-Pin habe ich nicht verbunden. Um den Kernel wissen zu lassen, dass ein DW1000 angeschlossen ist, ist außerdem ein angepasster Device Tree nötig. Siehe auch die Links unten.

EN: I only connected SPI and IRQ, the reset pin was not connected. To let the kernel know that there is a DW1000 connected, a modified device tree is necessary.

See
https://github.com/nyrocron/dw1000/blob/master/wiring/rpi_dwm.svg for wiring
https://github.com/nyrocron/dw1000/issues/1#issuecomment-223840100 for some more info on device tree/compiling

**Comment by ab0032** [comment]
I assume you must be using a different hardware then, that pulls up ext and rst. Thanks for the quick response. I will try it and report back.

**Comment by nyrocron** [comment]
I am just using a plain DWM1000.
