### ISSUE TITLE
dw1000 .dts and driver for compute module

### ISSUE THREAD

**Issue by yidingalan** [nyrocron/dw1000#3]
hi @nyrocron Just wondering if this driver/overlay file will work for RPI compute module

**Comment by nyrocron** [comment]
Don't have one to test, sorry.

**Comment by yidingalan** [comment]
Did you write the overlay file for dw1000 (rpi2) from scratch or is there a good template to follow? I want to get it working on compute module. It will be using the same interface SPI0

**Comment by nyrocron** [comment]
You can decompile an existing device tree using dtc and base it on that.

**Comment by yidingalan** [comment]
So I was testing this on PI2 and I followed your compiling instructions. When I run `RHOST=pi2-a RANR=1 make rstart`, it gave me this error
```
scp dw1000.ko pi2-a:
ssh: Could not resolve hostname pi2-a: Name or service not known
lost connection
Makefile:27: recipe for target 'rload' failed
make: *** [rload] Error 1
```

Do I need to change the hostname to my own one? I tried that and still got an error:
```
Cannot find device "dw0"
Makefile:36: recipe for target 'rstart' failed
make: *** [rstart] Error 1
```

The only thing I changed in the MAKEFILE is the KERNELDIR

**Comment by pelwell** [comment]
@nyrocron You might want to try a real dw1000 overlay - see [here](https://www.raspberrypi.org/forums/viewtopic.php?p=1078516#p1078516). I've not tested it, but it should work. If not, feel free to report back.

In return, can you help @yidingalan to use your build script?
