### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by VVHack** [nyrocron/dw1000#4]
I am a beginner in working with chips and micro controllers so please pardon my ignorance.  I am working on a project to develop a positioning system using DWM1000.  What exactly does the file DW1000.c do when working with the DW1000?  Also, I have worked with the chip using an Arduino and the SPI worked without any problems, on the Pi I used WiringPi, BCM2835 but the chip doesn't respond to it at all, what am I doing wrong?  Why does the SPI work on the Arduino and not on the Pi?
Urgent help needed 
Thank you

**Comment by nyrocron** [comment]
This is a Linux kernel module, not a generic library. When loaded the kernel module provides a network device. Some hints how to compile it can be found in https://github.com/nyrocron/dw1000/blob/master/COMPILING but you will probably have to adjust some things to use it with a newer kernel.

I currently do not have time and hardware to support this project so I can just give some hints from memory.
